#ifndef TALGORITHMSLIB_GLOBAL_H
#define TALGORITHMSLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TALGORITHMSLIB_LIBRARY)
#  define TALGORITHMSLIB_EXPORT Q_DECL_EXPORT
#else
#  define TALGORITHMSLIB_EXPORT Q_DECL_IMPORT
#endif

#endif // TALGORITHMSLIB_GLOBAL_H
